# Generated by Django 5.0.3 on 2024-03-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("Arbitrage", "Arbitrage"),
                            ("Long/Short Equity", "Long/Short Equity"),
                            ("Global Macro", "Global Macro"),
                        ],
                        max_length=100,
                    ),
                ),
                ("aum", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "currency_code",
                    models.CharField(choices=[("USD", "USD")], default="USD", max_length=3),
                ),
                ("inception_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
